image:
  file: Dockerfile

ports:
  - port: 4000
    onOpen: open-browser
tasks:
  - init: bundle update && bundle install
    command: bundle exec jekyll serve --host=0.0.0.0
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false