# Dependencies
highlighter:          rouge
markdown:             kramdown

# Permalinks
permalink:            pretty

# Setup
title:                majug
tagline:              'Mannheim Java User Group'
description:          'Community der Java Anwender in Mannheim und Rhein Neckar Dreieck'
url:                  https://majug.de
#baseurl:              /
events_baseurl:       /events/

author:
  name:               'majug'
  url:                https://majug.de
  twitter:            https://twitter.com/majug
  meetup:             https://www.meetup.com/mannheim-java-usergroup/

paginate:             5
paginate_path:        '/events/page:num'

# Custom vars
version:              2.1.0

github:
  repo:               https://github.com/majug/majug.github.io

# Allow Posts in the future
future:               true

# Gems needed
plugins:                 [jekyll-paginate]
